### ISSUE TITLE
"Invalid calling object" on IE11

### ISSUE THREAD

**Issue by Pikachews** [jeslage/react-pick-color#11]
![image](https://user-images.githubusercontent.com/5668416/103493188-94d80780-4de4-11eb-83f6-6144759da9c8.png)

IE11 probably isn't a priority for this library, but it would be great if it did work on it. 🙃

Feel free to close if there are no plans to make this work on IE11 though.

Thanks for this amazing library!

**Comment by Pikachews** [comment]
A similar error occurs when trying to do snapshot testing with it via Storybook:

![image](https://user-images.githubusercontent.com/5668416/103494196-66f5c180-4dea-11eb-90d3-b22be1521b6f.png)

**Comment by jeslage** [comment]
Hey @Pikachews, nice to hear that you like the library. 
Currently i do not plan to support the IE11, but nevertheless i will take a look at this. Especially the storybook + storyshots combination should work.
I will let you know if i found the issue and made a new release.

**Comment by jeslage** [comment]
Hey @Pikachews,

I thought about this issue a bit. Currently this package can't support IE11, because I am using CSS variables for the styling. So this would be a major rewrite to support IE11.

Regarding the story shots issue: Could you provide an example where I can reproduce this? 
I currently cannot reproduce it in my codebase.

Thank you!
